import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex max-w-7xl flex-col items-center justify-center gap-4 px-4 py-16 text-center">
        <h2 className="text-5xl mb-4 font-extrabold tracking-tight">
          Office of the Imperial Housing Authority
        </h2>
        <div className="mb-4 grid grid-cols-2">
          <img
            className="h-full"
            src="https://images.uesp.net/6/69/OB-map-Cyrodiil.jpg"
          />
          <img
            className="h-full"
            src="https://images.uesp.net/e/ef/SR-map-Skyrim.jpg"
          />
        </div>
        <div className="flex w-full items-center justify-between">
          <p className="text-left text-lg text-white">
            Welcome to the Imperial Housing Authority, your premier source for
            quality properties in Cyrodiil and Skyrim! Our experienced sales
            team is dedicated to helping you find the perfect home or investment
            property, whether you are a first-time buyer or an experienced real
            estate investor. As a government branch of the Septim Empire, we
            take great pride in providing affordable and accessible housing
            options for citizens across the realm. Our team of experts is here
            to guide you through the entire process, from initial property
            search to closing and beyond. We believe that everyone deserves a
            safe, comfortable, and affordable place to call home, and we are
            committed to making that dream a reality for you. Contact us today
            to learn more about our available properties and to start your
            journey to home ownership!
          </p>
          <img
            className="w-1/2 p-16"
            src="https://images.uesp.net/thumb/5/5b/OB-place-Imperial_City.jpg/800px-OB-place-Imperial_City.jpg"
          />
        </div>
        <h2 className="mb-4 text-2xl font-semibold tracking-tight text-white">Frequently Asked Questions</h2>
        <div className="text-left text-white">
          <p className="mb-4">
          Here at the Imperial Housing Authority, we want to be as transparent as possible about our methods in
          displaying information about our properties. These are some of the most often asked questions about our listings.
          </p>
          <ul className="list-disc">
            <p className="mb-2">Why do you only offer properties in Cyrodiil and Skyrim?</p>
            <li className="ml-4 max-w-3xl mb-4">
              The Imperial Housing Authority is a young organization, having only been established during the rule of Emperor Mede II.
              We are working on expanding our network into High Rock, and potentially parterning up with a sister organization for a collaboration
              in Hammerfell.
            </li>
            <p className="mb-2">Why are some properties in Skyrim marked as unavailable?</p>
            <li className="ml-4 max-w-3xl">
              Due to the current Stormcloak rebellion within Skyrim, some properties in holds that are aligned with the insurgents are not purchaseable.
            </li>
          </ul>
        </div>
      </div>
    </>
  );
};

export default About;