import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex flex-col items-center justify-center gap-4 px-4 py-16 text-center">
        <h1 className="text-6xl font-extrabold tracking-tight text-white">
          Imperial Housing Authority
        </h1>
        <h2 className="mb-16 text-2xl tracking-tight text-white">
          Browse, purchase, or earn beautiful homes across Cyrodiil and Skyrim.
        </h2>
        <div className="grid grid-cols-3 gap-4">
          <Link href="/listing/cheydinhal">
            <div className="p-4 text-left text-white">
              <img src="https://images.uesp.net/5/5a/OB-place-Cheydinhal_House_For_Sale.jpg" />
              <p className="mt-2 font-semibold">Cheydinhal</p>
              <p className="font-sm font-thin">15,000 septims</p>
            </div>
          </Link>
          <Link href="/listing/honeyside">
            <div className="p-4 text-left text-white">
              <img src="https://static.wikia.nocookie.net/elderscrolls/images/9/9f/My_Cheydinhal_House.png" />
              <p className="mt-2 font-semibold">Honeyside, Riften</p>
              <p className="font-sm font-thin">8,000 septims</p>
            </div>
          </Link>
          <Link href="/listing/proudspire">
            <div className="p-4 text-left text-white">
              <img src="https://static.wikia.nocookie.net/elderscrolls/images/9/9f/My_Cheydinhal_House.png" />
              <p className="mt-2 font-semibold">Proudspire, Solitude</p>
              <p className="font-sm font-thin">25,000 septims</p>
            </div>
          </Link>
        </div>
        <div className="mb-16">
          <button className="mx-4 rounded-lg bg-gray-800 p-4 text-white no-underline transition hover:bg-gray-700">
            Browse Homes!!
          </button>
        </div>
        <div className="mb-16 grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
          <Link
            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
            href="https://create.t3.gg/en/usage/first-steps"
            target="_blank"
          >
            <h3 className="text-2xl font-bold">Homes for all walks</h3>
            <div className="text-lg">
              From homes befitting lovers of all things dwemer, to vampires, to
              the growing family, we list and sell them all at a fair price.
            </div>
          </Link>
          <Link
            className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
            href="https://create.t3.gg/en/introduction"
            target="_blank"
          >
            <h3 className="text-2xl font-bold">Safety is guaranteed</h3>
            <div className="text-lg">
              Tamriel is a dangerous place, and we ensure homes are maintained,
              protected, and offer insurance on the home, as well as its
              occupants.
            </div>
          </Link>
        </div>
        <div className="flex flex-col items-center gap-2">
          <AuthShowcase />
        </div>
      </div>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.home.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
